/**
 * Lead scoring and AI sales brief generation.
 *
 * Score (0-100): measures how much digital work the business needs
 * — high score = hot lead for a web agency.
 *
 * Sales brief: short French-language call-prep note generated by Gemini.
 */

import { askGeminiText } from "../browser";
import type { LeadResult } from "../index";

// ---------------------------------------------------------------------------
// Scoring
// ---------------------------------------------------------------------------

export function computeLeadScore(lead: LeadResult): number {
  let score = 0;

  // ── Website gap (biggest opportunity) ──────────────────────────────────
  if (!lead.has_website || lead.website_quality === "none") {
    score += 35;
  } else {
    switch (lead.website_quality) {
      case "dead":
        score += 28;
        break;
      case "outdated":
        score += 22;
        break;
      case "poor":
        score += 16;
        break;
      case "decent":
        score += 8;
        break;
      case "good":
        score += 0;
        break;
    }
  }

  // ── Missing digital features ────────────────────────────────────────────
  if (lead.has_booking === false) score += 15;
  if (lead.has_https === false && lead.has_website) score += 10;
  if (lead.has_chatbot === false) score += 5;
  if (lead.has_meta_ads === false) score += 5;

  // ── Google reputation (good at business, bad at digital = hottest lead) ─
  const rating = parseFloat(lead.rating || "0");
  const reviews = parseInt(lead.review_count || "0", 10);
  if (rating >= 4.0 && reviews >= 10) score += 12;
  else if (rating >= 3.5 && reviews >= 5) score += 6;

  // ── Business size (sweet spot for an agency: 3-50 employees) ───────────
  const empStr = lead.employee_count || "";
  if (
    empStr.match(/^(3[-–à]5|6[-–à]9|10[-–à]19|20[-–à]49)/i) ||
    empStr.match(/^[3-9]$|^[1-4]\d$/)
  ) {
    score += 10;
  } else if (empStr.match(/^(1[-–à]2|0)/i) || empStr === "0") {
    score += 4; // solo/micro — possible but harder sale
  }

  // ── Business age (2-15 years: established but not too large) ───────────
  if (lead.creation_date) {
    const year = parseInt(lead.creation_date.slice(0, 4), 10);
    if (!isNaN(year)) {
      const age = new Date().getFullYear() - year;
      if (age >= 2 && age <= 15) score += 8;
      else if (age > 15 && age <= 30) score += 4;
    }
  }

  return Math.min(100, Math.max(0, score));
}

// ---------------------------------------------------------------------------
// Sales brief
// ---------------------------------------------------------------------------

export async function generateSalesBrief(
  lead: LeadResult,
  log: (msg: string) => void
): Promise<string> {
  try {
    const digitalGaps: string[] = [];

    if (!lead.has_website || lead.website_quality === "none") {
      digitalGaps.push("aucun site web");
    } else if (lead.website_quality === "dead") {
      digitalGaps.push("site web hors ligne");
    } else if (lead.website_quality === "outdated") {
      digitalGaps.push("site web obsolète");
    } else if (lead.website_quality === "poor") {
      digitalGaps.push("site web de mauvaise qualité");
    }

    if (lead.has_booking === false) digitalGaps.push("pas de réservation en ligne");
    if (lead.has_https === false && lead.has_website) digitalGaps.push("site non sécurisé (HTTP)");
    if (lead.has_chatbot === false) digitalGaps.push("pas de chat/bot");
    if (lead.has_meta_ads === false) digitalGaps.push("aucune publicité Meta");

    const ownerLine = lead.owner_name
      ? `Dirigeant : ${lead.owner_name}${lead.owner_role ? ` (${lead.owner_role})` : ""}.`
      : "Dirigeant inconnu.";

    const legalLine = [
      lead.company_type,
      lead.creation_date
        ? `créée en ${lead.creation_date.slice(0, 4)}`
        : null,
      lead.employee_count ? `${lead.employee_count} salariés` : null,
    ]
      .filter(Boolean)
      .join(", ");

    const rating = parseFloat(lead.rating || "0");
    const reviews = parseInt(lead.review_count || "0", 10);
    const ratingLine =
      rating > 0
        ? `Note Google : ${rating}/5 (${reviews} avis).`
        : "Pas de note Google visible.";

    const prompt = `Tu es un assistant commercial pour une agence web française. Prépare une note de 2-3 phrases pour briefer un commercial avant qu'il appelle cette entreprise.

Entreprise : ${lead.business_name}${lead.address ? ` — ${lead.address}` : ""}
${ownerLine}
Infos légales : ${legalLine || "non disponibles"}.
${ratingLine}
Lacunes digitales détectées : ${digitalGaps.length > 0 ? digitalGaps.join(", ") : "aucune identifiée pour l'instant"}.

Génère uniquement la note de briefing, en français, sans titre ni mise en forme. Sois précis et actionnable. Termine par l'angle de pitch principal.`;

    const brief = await askGeminiText(prompt);
    log(`[Scorer] ✓ Sales brief generated`);
    return brief;
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    log(`[Scorer] ✗ Brief generation failed: ${msg.slice(0, 80)}`);
    // Fallback: build a simple brief from available data without Gemini
    const gaps = [];
    if (!lead.has_website) gaps.push("pas de site web");
    if (lead.has_booking === false) gaps.push("pas de réservation");
    const name = lead.owner_name ? `Contacter ${lead.owner_name}` : "Contacter le dirigeant";
    return `${name} — ${lead.business_name}. ${gaps.length ? `Lacunes : ${gaps.join(", ")}.` : "Analyser la présence digitale."} Score : ${lead.potential_score ?? "—"}/100.`;
  }
}
