/**
 * Registers all available tools. Import this module to populate the registry.
 */

import "./pappers-search";
import "./societe-com-lookup";
import "./google-maps-search";
import "./google-search";
import "./pages-jaunes-search";
import "./facebook-lookup";
import "./linkedin-search";
import "./fb-ad-library";
import "./website-finder";
import "./website-audit";
import "./dirigeant-research";
import "./contact-page-scraper";
import "./scratchpad";
import "./save-lead";
import "./batch-website-check";
import "./batch-save-leads";
import "./ask-user";

// Agent v3 generic tools (always registered)
import "./todo";
import "./plan";
import "./reflection";
import "./memory";
import "./approval";
import "./web_fetch";
import "./web_search";
import "./replicate-image-generate";
import "./agentic-browse";
import "./gmail";
import "./calendar";

// Self-improvement & self-extension
import "./learn";
import "./tool-creator";
import "./repo";

// Agent OS (supervisor stack, façades, workspace read, MCP/workflow stubs)
import "./os-browser-suite";
import "./os-research-suite";
import "./os-workspace";
import "./os-corpus";
import "./os-mcp-workflow";
import "./os-knowledge";

// Agent-authored tools (auto-generated by the self-coding pack). The barrel
// file lists explicit imports so Next.js bundles them at build time. When
// the agent adds a new tool, it also updates that barrel.
import "./_generated";

export { getAllToolNames, getToolDefinitions, executeTool } from "../tool-registry";
