-- This migration is now merged into the apply script below.
-- The fix (SECURITY DEFINER) is baked directly into 010's function definition.
-- See: supabase/migrations/010_organization_foundation.sql line 48
